In [35]:
import math
import numpy as np
te=4
tn=5
x1=[0,500,0,500]
x2=[0,0,500,500]
x3=[250,250,250,250]

y1=[0,250,0,0]
y2=[250,250,0,250]
y3=[125,125,125,125]
E=210e3
pr=0.3
t=25
ke=[]

for i in range(te):
    A=(x1[i]*(y2[i]-y3[i])+x2[i]*(y3[i]-y1[i])+x3[i]*(y1[i]-y2[i]))/2
    Bi =y2[i]-y3[i]
    Bj =y3[i]-y1[i]
    Bm =y1[i]-y2[i]
    Gi =x3[i]-x2[i]
    Gj =x1[i]-x3[i]
    Gm =x2[i]-x1[i]
    B=[]
    B=np.array([[Bi, 0,Bj, 0,Bm,0],[0,Gi,0,Gj,0,Gm],[Gi,Bi,Gj,Bj,Gm,Bm]])/(2*A)
    Bt=B.T
    D=(E/(1-pr*pr))*np.array([[1,pr,0],[pr,1,0],[0,0,(1-pr)/2]])
    BtD=np.matmul(Bt,D)
    elst=t*A*np.matmul(BtD,B)
    ke.append(elst)    


gmat=[]    
gste1=np.zeros([2*tn,2*tn])
H1=ke[0]
for j in range(2*tn):
    for k in range(2*tn):
        if j==(2,3,4,5) or k==(2,3,4,5):
            gste1[j,k]=0
            
        else:
            if j<2 and k<2:
                gste1[j,k]=H1[j,k]
                
            if j<2 and k>5:
                gste1[j,k]=H1[j,k-4]
            if j>5 and k>5:
                gste1[j,k]=H1[j-4,k-4]
            if j>5 and k<2:
                gste1[j,k]=H1[j-4,k]
gste1=-gste1
gmat.append(gste1)

gste2=np.zeros([2*tn,2*tn])

H2=ke[1]
for j in range(2*tn):
    for k in range(2*tn):
        if j>3 and k>3:
            gste2[j,k]=H2[j-4,k-4] 
                  
gmat.append(gste2)

gste3=np.zeros([2*tn,2*tn])
H3=ke[2]
for j in range(2*tn):
    for k in range(2*tn):
        if j==(4,5,6,7) or k==(4,5,6,7):
            gste3[j,k]=0
            
        else:
            if j<4 and k<4:
                gste3[j,k]=H3[j,k]
                
            if j<4 and k>7:
                gste3[j,k]=H3[j,k-4]
            if j>7 and k>7:
                gste3[j,k]=H3[j-4,k-4]
            if j>7 and k<4:
                gste3[j,k]=H3[j-4,k]
gmat.append(gste3)

gste4=np.zeros([2*tn,2*tn])
H4=ke[3]
for j in range(2*tn):
    for k in range(2*tn):
        if j==(0,1,6,7) or k==(0,1,6,7):
            gste4[j,k]=0
        else:
            if j<6 and j>1 and k<6 and k>1:
                gste4[j,k]=H4[j-2,k-2]
                
            if j<6 and j>1 and k>7:
                gste4[j,k]=H4[j-2,k-4]
            if j>7 and k>7:
                gste4[j,k]=H4[j-4,k-4]
            if j>7 and k<6 and k>1:
                gste4[j,k]=H4[j-4,k-2]
gmat.append(gste4)

GST=np.zeros([2*tn,2*tn])
for mat in gmat:
    GST=GST+mat
print("Global Stiffness Matrix is :\n\n")    
print(GST)
#print(ke[1])
#print(gste1)

Global Stiffness Matrix is :


[[ 3461538.46153846  1875000.           288461.53846154   -72115.38461538
         0.                0.          -288461.53846154    72115.38461538
  -3461538.46153846 -1875000.        ]
 [ 1875000.          6274038.46153846    72115.38461538  2632211.53846154
         0.                0.           -72115.38461538 -2632211.53846154
  -1875000.         -6274038.46153846]
 [  288461.53846154    72115.38461538  3461538.46153846 -1875000.
   -288461.53846154   -72115.38461538        0.                0.
  -3461538.46153846  1875000.        ]
 [  -72115.38461538  2632211.53846154 -1875000.          6274038.46153846
     72115.38461538 -2632211.53846154        0.                0.
   1875000.         -6274038.46153846]
 [       0.                0.          -288461.53846154    72115.38461538
   3461538.46153846  1875000.           288461.53846154   -72115.38461538
  -3461538.46153846 -1875000.        ]
 [       0.                0.           -72115.38461538 -2

In [36]:
KTS=GST
KTS=np.delete(KTS,7,0)
KTS=np.delete(KTS,7,1)
KTS=np.delete(KTS,6,0)
KTS=np.delete(KTS,6,1)
KTS=np.delete(KTS,1,0)
KTS=np.delete(KTS,1,1)
KTS=np.delete(KTS,0,0)
KTS=np.delete(KTS,0,1)



In [37]:
f=1000*np.array([[9.375],[0],[9.375],[0],[0],[0]])
u=np.linalg.inv(KTS).dot(f)
print(f"u: \n{u}")

u: 
[[ 6.92834261e-03]
 [ 7.13904355e-04]
 [ 6.92834261e-03]
 [-7.13904355e-04]
 [ 3.27082221e-03]
 [ 1.30104261e-18]]


In [29]:
U=np.zeros((10,1))
U[2:6]=u[0:4]
U[8:10]=u[4:6]
print(U)
F=GST.dot(U)
print(f"\n{F}")

[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 6.92834261e-03]
 [ 7.13904355e-04]
 [ 6.92834261e-03]
 [-7.13904355e-04]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 3.27082221e-03]
 [ 1.30104261e-18]]

[[-9.37500000e+03]
 [-3.75400427e+03]
 [ 9.37500000e+03]
 [ 0.00000000e+00]
 [ 9.37500000e+03]
 [ 1.81898940e-12]
 [-9.37500000e+03]
 [ 3.75400427e+03]
 [ 7.27595761e-12]
 [ 3.63797881e-12]]


In [32]:
def LinearTriangleElementStresses(E,pr,xi,yi,xj,yj,xm,ym,p,u):
    A = (xi*(yj-ym) + xj*(ym-yi) + xm*(yi-yj))/2
    betai = yj-ym
    betaj = ym-yi
    betam = yi-yj
    gammai = xm-xj
    gammaj = xi-xm
    gammam = xj-xi
    B = np.array([[betai, 0, betaj, 0, betam, 0 ],[0, gammai, 0, gammaj, 0, gammam],[gammai, betai, gammaj, betaj, gammam, betam]])/(2*A);
    if p == int(1):
        D = (E/(1-pr*pr))*np.array([[1, pr, 0] , [pr, 1, 0], [0, 0, (1-pr)/2]])
    elif p == int(2):
        D = (E/(1+pr)/(1-2*pr))*np.array([[1-pr, pr, 0], [pr, 1-pr, 0], [0, 0, (1-2*pr)/2]])

    return D.dot(B).dot(u)

u1=[U[0],U[1],U[8],U[9],U[6],U[7]]
u2=[U[0],U[1],U[2],U[3],U[8],U[9]]
u3=[U[8],U[9],U[2],U[3],U[4],U[5]]
u4=[U[6],U[7],U[8],U[9],U[4],U[5]]

sigma1=LinearTriangleElementStresses(E,pr,0,0,0.25,0.125,0,0.25,1,u1)
sigma2=LinearTriangleElementStresses(E,pr,0,0,0.5,0,0.25,0.125,1,u2)
sigma3=LinearTriangleElementStresses(E,pr,0.25,0.125,0.5,0,0.5,0.25,1,u3)
sigma4=LinearTriangleElementStresses(E,pr,0,0.25,0.25,0.125,0.5,0.25,1,u4)
print(sigma1)
print(sigma2)
print(sigma3)
print(sigma4)
  
        

[[3.01922050e+03]
 [9.05766151e+02]
 [4.20336842e-13]]
[[3000.        ]
 [ 300.3203417 ]
 [  -9.61025093]]
[[2980.77949813]
 [-305.12546716]
 [   0.        ]]
[[3000.        ]
 [ 300.3203417 ]
 [   9.61025093]]


In [33]:
def LinearTriangleElementPStresses(sigma):
    R = (sigma[0] + sigma[1])/2
    Q = ((sigma[0] - sigma[1])/2)**2 + sigma[2]*sigma[2]
    M = 2*sigma[2]/(sigma[0] - sigma[1])
    s1 = R + np.sqrt(Q)
    s2 = R - np.sqrt(Q)
    theta = (np.arctan(M)/2)*180/np.pi
    s=np.matrix([s1, s2 , theta])
    return s

s1=LinearTriangleElementPStresses(sigma1)
print(s1)
s2=LinearTriangleElementPStresses(sigma2)
print(s2)
s3=LinearTriangleElementPStresses(sigma3)
print(s3)
s4=LinearTriangleElementPStresses(sigma4)
print(s4)


[[3.01922050e+03]
 [9.05766151e+02]
 [1.13953382e-14]]
[[ 3.00003421e+03]
 [ 3.00286132e+02]
 [-2.03956612e-01]]
[[2980.77949813]
 [-305.12546716]
 [   0.        ]]
[[3.00003421e+03]
 [3.00286132e+02]
 [2.03956612e-01]]
