In [1]:
E=210e6 #kN/m^2
mu=0.3
t=0.025 #m
w=3000 #kN/m^2

In [2]:
import mumpy as np
#STEP1 Discretizing
def LinearTriangleElementStiffness(E,mu,t,xi,yi,xj,yj,xm,ym,p):
    A = (xi*(yj-ym)+ xj*(ym-yi) + xm*(yi-yj))/2
    betai = yj-ym
    betaj = ym-yi
    betam = yi-yj
    gammai = xm-xj
    gammaj = xi-xm
    gammam = xj-xi
    B=np.asarray([[betai, 0 ,betaj, 0, betam, 0],[0, gammai, 0, gammaj, 0 ,gammam],[gammai,betai,gammaj,betaj,gammam,betam]])

    B=B*(1/(2*A))
    if p==1:
        D=(E/(1-mu*mu))*np.asarray([[1,mu,0],[mu,1,0],[0,0,(1-mu)/2]])
    elif p==2:
        D=(E/((1+mu)*(1-2*mu)))*np.asarray([[1-mu,mu,0],[mu,1-mu,0],[0,0,(1-2*mu)/2]])
    
    return t*A*np.dot(B.T,np.dot(D,B))
    



In [3]:
k1=LinearTriangleElementStiffness(E,mu,t,0,0,0.5,0.25,0,0.25,1)
print(k1)

[[ 2019230.76923077        0.                0.         -1009615.38461538
  -2019230.76923077  1009615.38461538]
 [       0.          5769230.76923077  -865384.61538462        0.
    865384.61538462 -5769230.76923077]
 [       0.          -865384.61538462  1442307.69230769        0.
  -1442307.69230769   865384.61538462]
 [-1009615.38461538        0.                0.           504807.69230769
   1009615.38461538  -504807.69230769]
 [-2019230.76923077   865384.61538462 -1442307.69230769  1009615.38461538
   3461538.46153846 -1875000.        ]
 [ 1009615.38461538 -5769230.76923077   865384.61538462  -504807.69230769
  -1875000.          6274038.46153846]]


In [4]:
k2=LinearTriangleElementStiffness(E,mu,t,0,0,0.5,0,0.5,0.25,1)
print(k2)

[[ 1442307.69230769        0.         -1442307.69230769   865384.61538462
         0.          -865384.61538462]
 [       0.           504807.69230769  1009615.38461538  -504807.69230769
  -1009615.38461538        0.        ]
 [-1442307.69230769  1009615.38461538  3461538.46153846 -1875000.
  -2019230.76923077   865384.61538462]
 [  865384.61538462  -504807.69230769 -1875000.          6274038.46153846
   1009615.38461538 -5769230.76923077]
 [       0.         -1009615.38461538 -2019230.76923077  1009615.38461538
   2019230.76923077        0.        ]
 [ -865384.61538462        0.           865384.61538462 -5769230.76923077
         0.          5769230.76923077]]


In [5]:
#STEP 2 Assembling
K = np.zeros((8, 8))


def LinearTriangleAssemble(K :np.ndarray, k, i, j, m):
    K[2*i-1-1, 2*i-1-1] = K[2*i-1-1, 2*i-1-1] + k[1-1, 1-1]
    K[2*i-1-1, 2*i-1] = K[2*i-1-1,  2*i-1] + k[1-1, 2-1]
    K[2*i-1-1, 2*j-1-1] = K[2*i-1-1,  2*j-1-1] + k[1-1, 3-1]
    K[2*i-1-1,  2*j-1] = K[2*i-1-1,  2*j-1] + k[1-1, 4-1]
    K[2*i-1-1,  2*m-1-1] = K[2*i-1-1,  2*m-1-1] + k[1-1, 5-1]
    K[2*i-1-1,  2*m-1] = K[2*i-1-1,  2*m-1] + k[1-1, 6-1]
    K[2*i-1, 2*i-1-1] = K[2*i-1, 2*i-1-1] + k[2-1, 1-1]
    K[2*i-1, 2*i-1] = K[2*i-1, 2*i-1] + k[2-1, 2-1]
    K[2*i-1, 2*j-1-1] = K[2*i-1, 2*j-1-1] + k[2-1, 3-1]
    K[2*i-1, 2*j-1] = K[2*i-1, 2*j-1] + k[2-1, 4-1]
    K[2*i-1, 2*m-1-1] = K[2*i-1, 2*m-1-1] + k[2-1, 5-1]
    K[2*i-1, 2*m-1] = K[2*i-1, 2*m-1] + k[2-1, 6-1]
    K[2*j-1-1, 2*i-1-1] = K[2*j-1-1,  2*i-1-1] + k[3-1, 1-1]
    K[2*j-1-1,  2*i-1] = K[2*j-1-1,  2*i-1] + k[3-1, 2-1]
    K[2*j-1-1,  2*j-1-1] = K[2*j-1-1,  2*j-1-1] + k[3-1, 3-1]
    K[2*j-1-1,  2*j-1] = K[2*j-1-1,  2*j-1] + k[3-1, 4-1]
    K[2*j-1-1,  2*m-1-1] = K[2*j-1-1,  2*m-1-1] + k[3-1, 5-1]
    K[2*j-1-1,  2*m-1] = K[2*j-1-1, 2*m-1] + k[3-1, 6-1]
    K[2*j-1, 2*i-1-1] = K[2*j-1, 2*i-1-1] + k[4-1, 1-1]
    K[2*j-1, 2*i-1] = K[2*j-1, 2*i-1] + k[4-1, 2-1]
    K[2*j-1, 2*j-1-1] = K[2*j-1, 2*j-1-1] + k[4-1, 3-1]
    K[2*j-1, 2*j-1] = K[2*j-1, 2*j-1] + k[4-1, 4-1]
    K[2*j-1, 2*m-1-1] = K[2*j-1, 2*m-1-1] + k[4-1, 5-1]
    K[2*j-1, 2*m-1] = K[2*j-1, 2*m-1] + k[4-1, 6-1]
    K[2*m-1-1,  2*i-1-1] = K[2*m-1-1,  2*i-1-1] + k[5-1, 1-1]
    K[2*m-1-1,  2*i-1] = K[2*m-1-1, 2*i-1] + k[5-1, 2-1]
    K[2*m-1-1,  2*j-1-1] = K[2*m-1-1,  2*j-1-1] + k[5-1, 3-1]
    K[2*m-1-1,  2*j-1] = K[2*m-1-1,  2*j-1] + k[5-1, 4-1]
    K[2*m-1-1,  2*m-1-1] = K[2*m-1-1,  2*m-1-1] + k[5-1, 5-1]
    K[2*m-1-1, 2*m-1] = K[2*m-1-1,  2*m-1] + k[5-1, 6-1]
    K[2*m-1, 2*i-1-1] = K[2*m-1, 2*i-1-1] + k[6-1, 1-1]
    K[2*m-1, 2*i-1] = K[2*m-1, 2*i-1] + k[6-1, 2-1]
    K[2*m-1, 2*j-1-1] = K[2*m-1, 2*j-1-1] + k[6-1, 3-1]
    K[2*m-1, 2*j-1] = K[2*m-1, 2*j-1] + k[6-1, 4-1]
    K[2*m-1, 2*m-1-1] = K[2*m-1, 2*m-1-1] + k[6-1, 5-1]
    K[2*m-1, 2*m-1] = K[2*m-1, 2*m-1] + k[6-1, 6-1]
    
    return K
    

In [6]:
K = np.zeros((8, 8))
K=LinearTriangleAssemble(K,k1,1,3,4)
K=LinearTriangleAssemble(K,k2,1,2,3)

print(K)

[[ 3461538.46153846        0.         -1442307.69230769   865384.61538462
         0.         -1875000.         -2019230.76923077  1009615.38461538]
 [       0.          6274038.46153846  1009615.38461538  -504807.69230769
  -1875000.                0.           865384.61538462 -5769230.76923077]
 [-1442307.69230769  1009615.38461538  3461538.46153846 -1875000.
  -2019230.76923077   865384.61538462        0.                0.        ]
 [  865384.61538462  -504807.69230769 -1875000.          6274038.46153846
   1009615.38461538 -5769230.76923077        0.                0.        ]
 [       0.         -1875000.         -2019230.76923077  1009615.38461538
   3461538.46153846        0.         -1442307.69230769   865384.61538462]
 [-1875000.                0.           865384.61538462 -5769230.76923077
         0.          6274038.46153846  1009615.38461538  -504807.69230769]
 [-2019230.76923077   865384.61538462        0.                0.
  -1442307.69230769  1009615.38461538  3461538.4

In [7]:
#STEP 4 Applying Bpundary conditions
U=np.zeros((8,1))
F=np.zeros((8,1))

#COnditions
F[2,0]=9.375
F[3,0]=0
F[4,0]=9.375
F[5,0]=0

#Partitioning matrices
Up=U[2:6]
Ux=U[[0,1,6,7],:]
Fp=F[2:6]
Kpp=K[2:6,2:6]
print(Kpp)
print(Fp)
Up=np.dot(np.linalg.inv(Kpp),Fp)

print(Up)
# Fx=np.add(np.dot(Kxp,Up),np.dot(Kxx,Ux))
# U=np.concatenate((Up,Ux))
# F=np.concatenate((Fp,Fx))



[[ 3461538.46153846 -1875000.         -2019230.76923077   865384.61538462]
 [-1875000.          6274038.46153846  1009615.38461538 -5769230.76923077]
 [-2019230.76923077  1009615.38461538  3461538.46153846        0.        ]
 [  865384.61538462 -5769230.76923077        0.          6274038.46153846]]
[[9.375]
 [0.   ]
 [9.375]
 [0.   ]]
[[7.11111747e-06]
 [1.11517786e-06]
 [6.53122498e-06]
 [4.46071143e-08]]


In [8]:
#STEP 6 Post Processing

#Add back calculated Up
U[2:6]=Up

#Calculate force
F=np.dot(K,U)
print(F)

[[-9.37500000e+00]
 [-5.62950360e+00]
 [ 9.37500000e+00]
 [-3.38618023e-15]
 [ 9.37500000e+00]
 [ 1.83186799e-15]
 [-9.37500000e+00]
 [ 5.62950360e+00]]


In [24]:
#Element stresses
def LinearTriangleElementStresses(E,mu,xi,yi,xj,yj,xm,ym,p,u):
    A = (xi*(yj-ym) + xj*(ym-yi) + xm*(yi-yj))/2
    betai = yj-ym
    betaj = ym-yi
    betam = yi-yj
    gammai = xm-xj
    gammaj = xi-xm
    gammam = xj-xi
    B = np.asarray([[betai, 0, betaj, 0, betam, 0],[0, gammai, 0, gammaj, 0 ,gammam],[ gammai, betai, gammaj, betaj ,gammam, betam]])/(2*A)
    if p == 1:
        D = (E/(1-mu*mu))*np.asarray([[1, mu, 0],[ mu, 1, 0],[ 0 ,0, (1-mu)/2]])
    elif p == 2:
        D = (E/((1+mu)*(1-2*mu)))*np.asarray([[1-mu, mu, 0],[ mu, 1-mu, 0],[ 0, 0, (1-2*mu)/2]])
  
    return np.dot(D,np.dot(B,u))
    

In [29]:
#Principal stresses
def LinearTriangleElementPStresses(sigma):
    R = (sigma[0] + sigma[1])/2
    Q = ((sigma[0] - sigma[1])/2)**2 + sigma[2]*sigma[2]
    M = 2*sigma[2]/(sigma[0] - sigma[1])
    s1 = R + np.sqrt(Q)
    s2 = R - np.sqrt(Q)
    theta = (np.arctan(M)/2)*180/np.pi
    return np.asarray([s1 , s2 , theta])

In [25]:
##STEP 7: element stresses

#Element disp vector
u1=np.asarray([U[0],U[1],U[4],U[5],U[6],U[7]])
u2=np.asarray([U[0],U[1],U[2],U[3],U[4],U[5]])

In [26]:
sigma1=LinearTriangleElementStresses(E,mu,0,0,0.5,0.25,0,0.25,1,u1)
print(sigma1)

[[3014.41152922]
 [ 904.32345877]
 [   7.20576461]]


In [27]:
sigma2=LinearTriangleElementStresses(E,mu,0,0,0.5,0,0.5,0.25,1,u2)
print(sigma2)

[[2985.58847078]
 [  -3.60288231]
 [  -7.20576461]]


In [31]:
#STEP 8 Principal stresses
s1=LinearTriangleElementPStresses(sigma1)
print(s1)

[[3.01443614e+03]
 [9.04298852e+02]
 [1.95656990e-01]]


In [32]:
s2=LinearTriangleElementPStresses(sigma2)
print(s2)

[[ 2.98560584e+03]
 [-3.62025247e+00]
 [-1.38116518e-01]]
