In [1]:
import numpy as np
class Node:
    """Node
        -Num= node id
        -Pos: Coordinate Position
        -Disp: [ux,uy]
        -Restrained[i]==1 if restrained 0 if unrestrained
        -Load Vector=[Px,Py]
        """
    def __init__(self,num,Pos,Disp=[0,0],Restr=[0,0],Load=[0,0]) -> None:
        self.Num=id
        self.Pos=np.asarray(Pos)
        self.Disp_vec=np.asarray(Disp)
        self.restrained=np.asarray(Restr)
        self.Load=np.asarray(Load)
    def set_Pos(self,Pos):
        self.Pos=Pos
    def get_Pos(self):
        return self.Pos
    def get_ID(self):
        return self.ID
    def get_Disp(self):
        return self.Disp_vec
    def get_Load(self):
        return self.Load
    def set_Load(self,Px,Py):
        self.Load=np.asarray([Px,Py])
    
class Bar_element:
    """Bar Element
        -E,A,L
        -K[2x2]=[[k -k],[-k,k]]
        -Theta (in degrees) from global axed"""
    def __init__(self,N1:Node,N2 :Node,E=1,A=1) -> None:
        self.L=np.linalg.norm(np.add(N2.get_Pos(),-1*N1.get_Pos()))
        self.N1=N1
        self.N2=N2
        self.E=E
        self.A=A
        self.K=E*A/self.L
        self.Theta=np.arctan(np.add(N2.get_Pos(),-1*N1.get_Pos())[1]/np.add(N2.get_Pos(),-1*N1.get_Pos())[0])*180/np.pi
        
    def get_local_k(self):
        #Returns local stiffness matrix [2x2]
        return np.asarray([[self.K,-1*self.K],[-1*self.K,self.K]])

    def get_global_k(self):
        #Return global stiffness matrix =[T]'*[K_Local]*[T]
        #T=[[cos()  sin()   0   0   ],
        #   [0      0   cos()   sin()]]
        c=np.cos(self.Theta*np.pi/180)
        s=np.sin(self.Theta*np.pi/180)
        T :np.ndarray=np.asarray([[c,s,0.0,0.0],[0.0,0.0,c,s]])
        K_Local=self.get_local_k()
        return np.dot(np.dot(T.T,K_Local),T)

    def set_E(self,E):
        self.E=E
    def set_A(self,A):
        self.A=A
    def get_E(self):
        return self.E
    def get_A(self):
        return self.A
    def get_Nodes(self):
        return [self.N1,self.N2]

In [18]:
N1=Node(1,[0,0],)
N2=Node(2,[1,0])

Elem=Bar_element(N1,N2)
print(Elem.get_global_k())
print(Elem.get_local_k())
print(Elem.Theta)
print(Elem.L)


[[ 1.  0. -1.  0.]
 [ 0.  0.  0.  0.]
 [-1.  0.  1.  0.]
 [ 0.  0.  0.  0.]]
[[ 1. -1.]
 [-1.  1.]]
0.0
1.0
