In [9]:
import numpy as np
import math
E=200000
A=0.005
node1=(0,0)
node2=(5,7)
node3=(5,0)
node4=(10,7)
node5=(10,0)
node6=(15,0)
members=[[node1,node2],[node1,node3],[node2,node3],[node2,node4],[node2,node5],[node3,node5],[node4,node5],[node4,node6],[node5,node6]]
for member in members:
    base=member[1][0]-member[0][0]
    height=member[1][1]-member[0][1]
    hypotenuese= math.sqrt(((member[1][0]-member[0][0])*(member[1][0]-member[0][0]))+((member[1][1]-member[0][1])*(member[1][1]-member[0][1])))
    C=base/hypotenuese
    S=height/hypotenuese
    K1=([[(C*C),(C*S),(-1*C*C),(-1*C*S)],[(C*S),(S*S),(-1*C*S),(-1*S*S)],[(-1*C*C),(-1*C*S),(C*C),(C*S)],[(-1*C*S),(-1*S*S),(C*S),(S*S)]])
    K2=(A*E)/(hypotenuese)
    K=(np.dot(K1,K2))
    print (K)

[[ 39.27285093  54.9819913  -39.27285093 -54.9819913 ]
 [ 54.9819913   76.97478782 -54.9819913  -76.97478782]
 [-39.27285093 -54.9819913   39.27285093  54.9819913 ]
 [-54.9819913  -76.97478782  54.9819913   76.97478782]]
[[ 200.    0. -200.    0.]
 [   0.    0.    0.    0.]
 [-200.    0.  200.    0.]
 [   0.    0.    0.    0.]]
[[   0.            0.            0.            0.        ]
 [   0.          142.85714286    0.         -142.85714286]
 [   0.            0.            0.            0.        ]
 [   0.         -142.85714286    0.          142.85714286]]
[[ 200.    0. -200.    0.]
 [   0.    0.    0.    0.]
 [-200.    0.  200.    0.]
 [   0.    0.    0.    0.]]
[[ 39.27285093 -54.9819913  -39.27285093  54.9819913 ]
 [-54.9819913   76.97478782  54.9819913  -76.97478782]
 [-39.27285093  54.9819913   39.27285093 -54.9819913 ]
 [ 54.9819913  -76.97478782 -54.9819913   76.97478782]]
[[ 200.    0. -200.    0.]
 [   0.    0.    0.    0.]
 [-200.    0.  200.    0.]
 [   0.    0.    0.   