In [18]:
import numpy as np
import math
E=200000
A=0.005
nodes=np.zeros((6,2))
members=np.zeros((9,2))
nodes=[[0,0],[5,7],[5,0],[10,7],[10,0],[15,0]]
members=[[0,1],[0,2],[1,2],[1,3],[1,4],[2,4],[3,4],[3,5],[4,5]]
strucMat=np.zeros((12,12))
for i in range(0,9):
    fnode=members[i][1]
    snode=members[i][0]
    base=nodes[fnode][0]-nodes[snode][0]
    height=nodes[fnode][1]-nodes[snode][1]
    hypotenuese=math.sqrt((base**2)+(height**2))
    C=base/hypotenuese
    S=height/hypotenuese
    K1=np.zeros((4,4))
    K1=[[(C**2),(C*S),(-C**2),(-C*S)],[(C*S),(S*S),(-C*S),(-S*S)],[(-C*C),(-C*S),(C*C),(C*S)],[(-C*S),(-S*S),(C*S),(S*S)]]
    K2=(A*E)/(hypotenuese)
    K=np.multiply(K1,K2)
    print(K)
    expandedMat=np.zeros((12,12))
    for 


[[ 39.27285093  54.9819913  -39.27285093 -54.9819913 ]
 [ 54.9819913   76.97478782 -54.9819913  -76.97478782]
 [-39.27285093 -54.9819913   39.27285093  54.9819913 ]
 [-54.9819913  -76.97478782  54.9819913   76.97478782]]
[[ 200.    0. -200.   -0.]
 [   0.    0.   -0.   -0.]
 [-200.   -0.  200.    0.]
 [  -0.   -0.    0.    0.]]
[[   0.           -0.           -0.            0.        ]
 [  -0.          142.85714286    0.         -142.85714286]
 [  -0.            0.            0.           -0.        ]
 [   0.         -142.85714286   -0.          142.85714286]]
[[ 200.    0. -200.   -0.]
 [   0.    0.   -0.   -0.]
 [-200.   -0.  200.    0.]
 [  -0.   -0.    0.    0.]]
[[ 39.27285093 -54.9819913  -39.27285093  54.9819913 ]
 [-54.9819913   76.97478782  54.9819913  -76.97478782]
 [-39.27285093  54.9819913   39.27285093 -54.9819913 ]
 [ 54.9819913  -76.97478782 -54.9819913   76.97478782]]
[[ 200.    0. -200.   -0.]
 [   0.    0.   -0.   -0.]
 [-200.   -0.  200.    0.]
 [  -0.   -0.    0.   