In [1]:
import numpy as np
E=210e6
t=0.025
NU=0.3

In [2]:
def LinearTriangleElementStiffness(E,NU,t,xi,yi,xj,yj,xm,ym,p):
    A = (xi*(yj-ym) + xj*(ym-yi) + xm*(yi-yj))/2
    betai = yj-ym
    betaj = ym-yi
    betam = yi-yj
    gammai = xm-xj
    gammaj = xi-xm
    gammam = xj-xi
    B= 1/(2*A)*np.array([[betai, 0, betaj, 0, betam, 0],[0, gammai, 0, gammaj, 0, gammam],[gammai, betai, gammaj, betaj, gammam, betam]])
    if p==int(1):
        D= (E/(1-NU*NU))*np.array([[1, NU, 0], [NU, 1, 0] , [0, 0, (1-NU)/2]])
    elif p==int(2):
        D= (E/(1+NU)/(1-2*NU))*np.array([[1-NU, NU, 0], [NU, 1-NU, 0], [0, 0, (1-2*NU)/2]])
    else:
        None
    k=t*A*(B.T.dot(D).dot(B))
    return k

k1= LinearTriangleElementStiffness(E,NU,t,0,0,0.25,0.125,0,0.25,1)
k2= LinearTriangleElementStiffness(E,NU,t,0,0,0.5,0,0.25,0.125,1)
k3= LinearTriangleElementStiffness(E,NU,t,0.25,0.125,0.5,0,0.5,0.25,1)
k4= LinearTriangleElementStiffness(E,NU,t,0,0.25,0.25,0.125,0.5,0.25,1)


In [3]:
K=np.zeros((10,10))
def LinearTriangleAssemble(K,k,i,j,m):
    K[2*i-2][2*i-2] += k[0][0]
    K[2*i-2][2*i-1] += k[0][1]
    K[2*i-2][2*j-2] += k[0][2]
    K[2*i-2][2*j-1] += k[0][3]
    K[2*i-2][2*m-2] += k[0][4]
    K[2*i-2][2*m-1] += k[0][5]

    K[2*i-1][2*i-2] += k[1][0]
    K[2*i-1][2*i-1] += k[1][1]
    K[2*i-1][2*j-2] += k[1][2]
    K[2*i-1][2*j-1] += k[1][3]
    K[2*i-1][2*m-2] += k[1][4]
    K[2*i-1][2*m-1] += k[1][5]

    K[2*j-2][2*i-2] += k[2][0]
    K[2*j-2][2*i-1] += k[2][1]
    K[2*j-2][2*j-2] += k[2][2]
    K[2*j-2][2*j-1] += k[2][3]
    K[2*j-2][2*m-2] += k[2][4]
    K[2*j-2][2*m-1] += k[2][5]

    K[2*j-1][2*i-2] += k[3][0]
    K[2*j-1][2*i-1] += k[3][1]
    K[2*j-1][2*j-2] += k[3][2]
    K[2*j-1][2*j-1] += k[3][3]
    K[2*j-1][2*m-2] += k[3][4]
    K[2*j-1][2*m-1] += k[3][5]

    K[2*m-2][2*i-2] += k[4][0]
    K[2*m-2][2*i-1] += k[4][1]
    K[2*m-2][2*j-2] += k[4][2]
    K[2*m-2][2*j-1] += k[4][3]
    K[2*m-2][2*m-2] += k[4][4]
    K[2*m-2][2*m-1] += k[4][5]

    K[2*m-1][2*i-2] += k[5][0]
    K[2*m-1][2*i-1] += k[5][1]
    K[2*m-1][2*j-2] += k[5][2]
    K[2*m-1][2*j-1] += k[5][3]
    K[2*m-1][2*m-2] += k[5][4]
    K[2*m-1][2*m-1] += k[5][5]

    return K

K = LinearTriangleAssemble(K,k1,1,5,4)
K = LinearTriangleAssemble(K,k2,1,2,5)
K = LinearTriangleAssemble(K,k3,5,2,3)
K = LinearTriangleAssemble(K,k4,4,5,3)
print(f"Global Stiffness Matrix:\n{K}")



Global Stiffness Matrix:
[[ 3461538.46153846  1875000.           288461.53846154   -72115.38461538
         0.                0.          -288461.53846154    72115.38461538
  -3461538.46153846 -1875000.        ]
 [ 1875000.          6274038.46153846    72115.38461538  2632211.53846154
         0.                0.           -72115.38461538 -2632211.53846154
  -1875000.         -6274038.46153846]
 [  288461.53846154    72115.38461538  3461538.46153846 -1875000.
   -288461.53846154   -72115.38461538        0.                0.
  -3461538.46153846  1875000.        ]
 [  -72115.38461538  2632211.53846154 -1875000.          6274038.46153846
     72115.38461538 -2632211.53846154        0.                0.
   1875000.         -6274038.46153846]
 [       0.                0.          -288461.53846154    72115.38461538
   3461538.46153846  1875000.           288461.53846154   -72115.38461538
  -3461538.46153846 -1875000.        ]
 [       0.                0.           -72115.38461538 -2632211

In [4]:
k=np.delete(K,7,0)
k=np.delete(k,7,1)
k=np.delete(k,6,0)
k=np.delete(k,6,1)
k=np.delete(k,1,0)
k=np.delete(k,1,1)
k=np.delete(k,0,0)
k=np.delete(k,0,1)
print(k)
f=np.array([[9.375],[0],[9.375],[0],[0],[0]])
u=np.linalg.inv(k).dot(f)
print(f"u: \n{u}")

[[ 3461538.46153846 -1875000.          -288461.53846154   -72115.38461538
  -3461538.46153846  1875000.        ]
 [-1875000.          6274038.46153846    72115.38461538 -2632211.53846154
   1875000.         -6274038.46153846]
 [ -288461.53846154    72115.38461538  3461538.46153846  1875000.
  -3461538.46153846 -1875000.        ]
 [  -72115.38461538 -2632211.53846154  1875000.          6274038.46153846
  -1875000.         -6274038.46153846]
 [-3461538.46153846  1875000.         -3461538.46153846 -1875000.
  13846153.84615384        0.        ]
 [ 1875000.         -6274038.46153846 -1875000.         -6274038.46153846
         0.         25096153.84615384]]
u: 
[[ 6.92834261e-06]
 [ 7.13904355e-07]
 [ 6.92834261e-06]
 [-7.13904355e-07]
 [ 3.27082221e-06]
 [ 4.23516474e-22]]


In [5]:
U=np.zeros((10,1))
U[2:6]=u[0:4]
U[8:10]=u[4:6]
print(U)
F=K.dot(U)
print(f"\n{F}")

[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 6.92834261e-06]
 [ 7.13904355e-07]
 [ 6.92834261e-06]
 [-7.13904355e-07]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 3.27082221e-06]
 [ 4.23516474e-22]]

[[-9.37500000e+00]
 [-3.75400427e+00]
 [ 9.37500000e+00]
 [ 2.66453526e-15]
 [ 9.37500000e+00]
 [ 7.99360578e-15]
 [-9.37500000e+00]
 [ 3.75400427e+00]
 [ 0.00000000e+00]
 [-1.42403612e-14]]


In [6]:
def LinearTriangleElementStresses(E,NU,xi,yi,xj,yj,xm,ym,p,u):
    A = (xi*(yj-ym) + xj*(ym-yi) + xm*(yi-yj))/2
    betai = yj-ym
    betaj = ym-yi
    betam = yi-yj
    gammai = xm-xj
    gammaj = xi-xm
    gammam = xj-xi
    B = np.array([[betai, 0, betaj, 0, betam, 0 ],[0, gammai, 0, gammaj, 0, gammam],[gammai, betai, gammaj, betaj, gammam, betam]])/(2*A);
    if p == int(1):
        D = (E/(1-NU*NU))*np.array([[1, NU, 0] , [NU, 1, 0], [0, 0, (1-NU)/2]])
    elif p == int(2):
        D = (E/(1+NU)/(1-2*NU))*np.array([[1-NU, NU, 0], [NU, 1-NU, 0], [0, 0, (1-2*NU)/2]])

    return D.dot(B).dot(u)

u1=[U[0],U[1],U[8],U[9],U[6],U[7]]
u2=[U[0],U[1],U[2],U[3],U[8],U[9]]
u3=[U[8],U[9],U[2],U[3],U[4],U[5]]
u4=[U[6],U[7],U[8],U[9],U[4],U[5]]

sigma1=LinearTriangleElementStresses(E,NU,0,0,0.25,0.125,0,0.25,1,u1)
sigma2=LinearTriangleElementStresses(E,NU,0,0,0.5,0,0.25,0.125,1,u2)
sigma3=LinearTriangleElementStresses(E,NU,0.25,0.125,0.5,0,0.5,0.25,1,u3)
sigma4=LinearTriangleElementStresses(E,NU,0,0.25,0.25,0.125,0.5,0.25,1,u4)
print(sigma1)
print(sigma2)
print(sigma3)
print(sigma4)


[[3.01922050e+03]
 [9.05766151e+02]
 [1.36828399e-13]]
[[3000.        ]
 [ 300.3203417 ]
 [  -9.61025093]]
[[ 2.98077950e+03]
 [-3.05125467e+02]
 [ 8.81072992e-13]]
[[3000.        ]
 [ 300.3203417 ]
 [   9.61025093]]


In [7]:
def LinearTriangleElementPStresses(sigma):
    R = (sigma[0] + sigma[1])/2
    Q = ((sigma[0] - sigma[1])/2)**2 + sigma[2]*sigma[2]
    M = 2*sigma[2]/(sigma[0] - sigma[1])
    s1 = R + np.sqrt(Q)
    s2 = R - np.sqrt(Q)
    theta = (np.arctan(M)/2)*180/np.pi
    s=np.matrix([s1, s2 , theta])
    return s

s1=LinearTriangleElementPStresses(sigma1)
print(s1)
s2=LinearTriangleElementPStresses(sigma2)
print(s2)
s3=LinearTriangleElementPStresses(sigma3)
print(s3)
s4=LinearTriangleElementPStresses(sigma4)
print(s4)


[[3.01922050e+03]
 [9.05766151e+02]
 [3.70941998e-15]]
[[ 3.00003421e+03]
 [ 3.00286132e+02]
 [-2.03956612e-01]]
[[ 2.98077950e+03]
 [-3.05125467e+02]
 [ 1.53631235e-14]]
[[3.00003421e+03]
 [3.00286132e+02]
 [2.03956612e-01]]
