In [4]:
E=210e6 #kN/m^2
mu=0.3  #poissons ratio
t=0.025 #m
w=3000 #kN/m^2

In [5]:
#STEP1 CREATING MEMBER STIFFNESS MATRICES 
import numpy as np
"""Basic Functions"""

def LinearTriangleElementStiffness(E,mu,t,xi,yi,xj,yj,xm,ym,p):
    """Creates CST stiffness matrix
        p==1 for plane stress
        p==2 for plane strain"""
    A = (xi*(yj-ym)+ xj*(ym-yi) + xm*(yi-yj))/2
    betai = yj-ym
    betaj = ym-yi
    betam = yi-yj
    gammai = xm-xj
    gammaj = xi-xm
    gammam = xj-xi
    B=np.asarray([[betai, 0 ,betaj, 0, betam, 0],[0, gammai, 0, gammaj, 0 ,gammam],[gammai,betai,gammaj,betaj,gammam,betam]])

    B=B*(1/(2*A))
    if p==1:
        D=(E/(1-mu*mu))*np.asarray([[1,mu,0],[mu,1,0],[0,0,(1-mu)/2]])
    elif p==2:
        D=(E/((1+mu)*(1-2*mu)))*np.asarray([[1-mu,mu,0],[mu,1-mu,0],[0,0,(1-2*mu)/2]])
    
    return t*A*np.dot(B.T,np.dot(D,B))
    



In [6]:
k1=LinearTriangleElementStiffness(E,mu,t,0,0,0.5,0.25,0,0.25,1)
print("Element1 stiffness matrix")
print(k1)

Element1 stiffness matrix
[[ 2019230.76923077        0.                0.         -1009615.38461538
  -2019230.76923077  1009615.38461538]
 [       0.          5769230.76923077  -865384.61538462        0.
    865384.61538462 -5769230.76923077]
 [       0.          -865384.61538462  1442307.69230769        0.
  -1442307.69230769   865384.61538462]
 [-1009615.38461538        0.                0.           504807.69230769
   1009615.38461538  -504807.69230769]
 [-2019230.76923077   865384.61538462 -1442307.69230769  1009615.38461538
   3461538.46153846 -1875000.        ]
 [ 1009615.38461538 -5769230.76923077   865384.61538462  -504807.69230769
  -1875000.          6274038.46153846]]


In [7]:
k2=LinearTriangleElementStiffness(E,mu,t,0,0,0.5,0,0.5,0.25,1)
print("Element2 stiffness matrix")
print(k2)

Element2 stiffness matrix
[[ 1442307.69230769        0.         -1442307.69230769   865384.61538462
         0.          -865384.61538462]
 [       0.           504807.69230769  1009615.38461538  -504807.69230769
  -1009615.38461538        0.        ]
 [-1442307.69230769  1009615.38461538  3461538.46153846 -1875000.
  -2019230.76923077   865384.61538462]
 [  865384.61538462  -504807.69230769 -1875000.          6274038.46153846
   1009615.38461538 -5769230.76923077]
 [       0.         -1009615.38461538 -2019230.76923077  1009615.38461538
   2019230.76923077        0.        ]
 [ -865384.61538462        0.           865384.61538462 -5769230.76923077
         0.          5769230.76923077]]


In [9]:
#STEP 2 ASSEMBLING
K = np.zeros((8, 8))    #Global stiffness matrix 

def LinearTriangleAssemble(K :np.ndarray, k, i, j, m):
    """Step Assembly of k(one member stiffness matrix) into K(Global stiffness)"""
    K[2*i-1-1, 2*i-1-1] = K[2*i-1-1, 2*i-1-1] + k[1-1, 1-1]
    K[2*i-1-1, 2*i-1] = K[2*i-1-1,  2*i-1] + k[1-1, 2-1]
    K[2*i-1-1, 2*j-1-1] = K[2*i-1-1,  2*j-1-1] + k[1-1, 3-1]
    K[2*i-1-1,  2*j-1] = K[2*i-1-1,  2*j-1] + k[1-1, 4-1]
    K[2*i-1-1,  2*m-1-1] = K[2*i-1-1,  2*m-1-1] + k[1-1, 5-1]
    K[2*i-1-1,  2*m-1] = K[2*i-1-1,  2*m-1] + k[1-1, 6-1]
    K[2*i-1, 2*i-1-1] = K[2*i-1, 2*i-1-1] + k[2-1, 1-1]
    K[2*i-1, 2*i-1] = K[2*i-1, 2*i-1] + k[2-1, 2-1]
    K[2*i-1, 2*j-1-1] = K[2*i-1, 2*j-1-1] + k[2-1, 3-1]
    K[2*i-1, 2*j-1] = K[2*i-1, 2*j-1] + k[2-1, 4-1]
    K[2*i-1, 2*m-1-1] = K[2*i-1, 2*m-1-1] + k[2-1, 5-1]
    K[2*i-1, 2*m-1] = K[2*i-1, 2*m-1] + k[2-1, 6-1]
    K[2*j-1-1, 2*i-1-1] = K[2*j-1-1,  2*i-1-1] + k[3-1, 1-1]
    K[2*j-1-1,  2*i-1] = K[2*j-1-1,  2*i-1] + k[3-1, 2-1]
    K[2*j-1-1,  2*j-1-1] = K[2*j-1-1,  2*j-1-1] + k[3-1, 3-1]
    K[2*j-1-1,  2*j-1] = K[2*j-1-1,  2*j-1] + k[3-1, 4-1]
    K[2*j-1-1,  2*m-1-1] = K[2*j-1-1,  2*m-1-1] + k[3-1, 5-1]
    K[2*j-1-1,  2*m-1] = K[2*j-1-1, 2*m-1] + k[3-1, 6-1]
    K[2*j-1, 2*i-1-1] = K[2*j-1, 2*i-1-1] + k[4-1, 1-1]
    K[2*j-1, 2*i-1] = K[2*j-1, 2*i-1] + k[4-1, 2-1]
    K[2*j-1, 2*j-1-1] = K[2*j-1, 2*j-1-1] + k[4-1, 3-1]
    K[2*j-1, 2*j-1] = K[2*j-1, 2*j-1] + k[4-1, 4-1]
    K[2*j-1, 2*m-1-1] = K[2*j-1, 2*m-1-1] + k[4-1, 5-1]
    K[2*j-1, 2*m-1] = K[2*j-1, 2*m-1] + k[4-1, 6-1]
    K[2*m-1-1,  2*i-1-1] = K[2*m-1-1,  2*i-1-1] + k[5-1, 1-1]
    K[2*m-1-1,  2*i-1] = K[2*m-1-1, 2*i-1] + k[5-1, 2-1]
    K[2*m-1-1,  2*j-1-1] = K[2*m-1-1,  2*j-1-1] + k[5-1, 3-1]
    K[2*m-1-1,  2*j-1] = K[2*m-1-1,  2*j-1] + k[5-1, 4-1]
    K[2*m-1-1,  2*m-1-1] = K[2*m-1-1,  2*m-1-1] + k[5-1, 5-1]
    K[2*m-1-1, 2*m-1] = K[2*m-1-1,  2*m-1] + k[5-1, 6-1]
    K[2*m-1, 2*i-1-1] = K[2*m-1, 2*i-1-1] + k[6-1, 1-1]
    K[2*m-1, 2*i-1] = K[2*m-1, 2*i-1] + k[6-1, 2-1]
    K[2*m-1, 2*j-1-1] = K[2*m-1, 2*j-1-1] + k[6-1, 3-1]
    K[2*m-1, 2*j-1] = K[2*m-1, 2*j-1] + k[6-1, 4-1]
    K[2*m-1, 2*m-1-1] = K[2*m-1, 2*m-1-1] + k[6-1, 5-1]
    K[2*m-1, 2*m-1] = K[2*m-1, 2*m-1] + k[6-1, 6-1]
    
    return K
    

In [10]:
K = np.zeros((8, 8))
#Assembling two Linear Triangle
K=LinearTriangleAssemble(K,k1,1,3,4)
K=LinearTriangleAssemble(K,k2,1,2,3)
print("Global Stiffness Matrix")
print(K)

Global Stiffness Matrix
[[ 3461538.46153846        0.         -1442307.69230769   865384.61538462
         0.         -1875000.         -2019230.76923077  1009615.38461538]
 [       0.          6274038.46153846  1009615.38461538  -504807.69230769
  -1875000.                0.           865384.61538462 -5769230.76923077]
 [-1442307.69230769  1009615.38461538  3461538.46153846 -1875000.
  -2019230.76923077   865384.61538462        0.                0.        ]
 [  865384.61538462  -504807.69230769 -1875000.          6274038.46153846
   1009615.38461538 -5769230.76923077        0.                0.        ]
 [       0.         -1875000.         -2019230.76923077  1009615.38461538
   3461538.46153846        0.         -1442307.69230769   865384.61538462]
 [-1875000.                0.           865384.61538462 -5769230.76923077
         0.          6274038.46153846  1009615.38461538  -504807.69230769]
 [-2019230.76923077   865384.61538462        0.                0.
  -1442307.69230769  100

In [13]:
##STEP 3 Applying Bpundary conditions

U=np.zeros((8,1))   #Disp vec
F=np.zeros((8,1))   #Force vec

#COnditions
F[2,0]=9.375
F[3,0]=0
F[4,0]=9.375
F[5,0]=0

#Partitioning matrices according to known and unknown displacements
Up=U[2:6]
Fp=F[2:6]
Kpp=K[2:6,2:6]

#Calculate Up=(Kpp^-1)*Fp
Up=np.dot(np.linalg.inv(Kpp),Fp)
print("Nodal Displacements of [U2x U2y U3x U3y]' (in m)")
print(Up*1e5)




Nodal Displacements of [U2x U2y U3x U3y]' (in m)
[[0.71111175]
 [0.11151779]
 [0.6531225 ]
 [0.00446071]]


In [15]:
#STEP 4 Post Processing

#Add back calculated Up
U[2:6]=Up

#Calculate force
F=np.dot(K,U)
print("Force Vector (in kN)")
print(F)

Force Vector (in kN)
[[-9.37500000e+00]
 [-5.62950360e+00]
 [ 9.37500000e+00]
 [-3.38618023e-15]
 [ 9.37500000e+00]
 [ 1.83186799e-15]
 [-9.37500000e+00]
 [ 5.62950360e+00]]


In [17]:
##STEP5 Element Stresses
#Element stresses
def LinearTriangleElementStresses(E,mu,xi,yi,xj,yj,xm,ym,p,u):
    A = (xi*(yj-ym) + xj*(ym-yi) + xm*(yi-yj))/2
    betai = yj-ym
    betaj = ym-yi
    betam = yi-yj
    gammai = xm-xj
    gammaj = xi-xm
    gammam = xj-xi
    B = np.asarray([[betai, 0, betaj, 0, betam, 0],[0, gammai, 0, gammaj, 0 ,gammam],[ gammai, betai, gammaj, betaj ,gammam, betam]])/(2*A)
    if p == 1:
        D = (E/(1-mu*mu))*np.asarray([[1, mu, 0],[ mu, 1, 0],[ 0 ,0, (1-mu)/2]])
    elif p == 2:
        D = (E/((1+mu)*(1-2*mu)))*np.asarray([[1-mu, mu, 0],[ mu, 1-mu, 0],[ 0, 0, (1-2*mu)/2]])
  
    return np.dot(D,np.dot(B,u))
    

In [18]:
#Principal stresses
def LinearTriangleElementPStresses(sigma):
    R = (sigma[0] + sigma[1])/2
    Q = ((sigma[0] - sigma[1])/2)**2 + sigma[2]*sigma[2]
    M = 2*sigma[2]/(sigma[0] - sigma[1])
    s1 = R + np.sqrt(Q)
    s2 = R - np.sqrt(Q)
    theta = (np.arctan(M)/2)*180/np.pi
    return np.asarray([s1 , s2 , theta])

In [19]:
##STEP 6: element stresses calc

#Element disp vector
u1=np.asarray([U[0],U[1],U[4],U[5],U[6],U[7]])
u2=np.asarray([U[0],U[1],U[2],U[3],U[4],U[5]])

In [24]:
sigma1=LinearTriangleElementStresses(E,mu,0,0,0.5,0.25,0,0.25,1,u1)
print("Element 1 stress(in Mpa)[sigma_x sigma_y tau_xy]")
print(sigma1)

Element 1 stress(in Mpa)[sigma_x sigma_y tau_xy]
[[3014.41152922]
 [ 904.32345877]
 [   7.20576461]]


In [25]:
sigma2=LinearTriangleElementStresses(E,mu,0,0,0.5,0,0.5,0.25,1,u2)
print("Element 2 stress(in Mpa)[sigma_x sigma_y tau_xy]")

print(sigma2)

Element 2 stress(in Mpa)[sigma_x sigma_y tau_xy]
[[2985.58847078]
 [  -3.60288231]
 [  -7.20576461]]


In [29]:
#STEP 8 Principal stresses
s1=LinearTriangleElementPStresses(sigma1)
print("Element 1 principal stress(in Mpa)")
print(s1)

Element 1 principal stress(in Mpa)
[[3.01443614e+03]
 [9.04298852e+02]
 [1.95656990e-01]]


In [28]:
s2=LinearTriangleElementPStresses(sigma2)
print("Element 2 principal stress(in Mpa)")
print(s2)

Element 2 principal stress(in Mpa)
[[ 2.98560584e+03]
 [-3.62025247e+00]
 [-1.38116518e-01]]
